apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-lbc
  namespace: argocd
  # The finalizer enables cascading deletes (deleting this app deletes its resources)
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  # The Argo CD project this application belongs to
  project: default

  source:
    chart: aws-load-balancer-controller
    repoURL: https://aws.github.io/eks-charts
    targetRevision: 3.5.0 # chart-version
    helm:
      # --set
      values: |
        clusterName: roboshop
        region: us-east-1
        serviceAccount:
          create: false
          name: aws-load-balancer-controller

  # Destination configuration pointing to the target cluster and namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true       # Automatically deletes resources no longer in Git
      selfHeal: true  