apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-classes
  namespace: argocd
  # The finalizer enables cascading deletes (deleting this app deletes its resources)
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  # The Argo CD project this application belongs to
  project: default

  source:
    repoURL: https://github.com/shajahan-devops1/Argocd-eks-cluster.git
    targetRevision: main
    path: applications/cluster/sc

  # Destination configuration pointing to the target cluster and namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true       # Automatically deletes resources no longer in Git
      selfHeal: true  